export const WEEKLY_ROUTINES = {
  Monday: [
    { title: "MONDAY", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Opening the office", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to open", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "10am-11am", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: " Check emails and reply to any new emails from last night and this morning", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Open up google chats and keep it open all day ", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check homeless support emails", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check office mobile/ landline returns any missed calls and reply to messages and whatsapp.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Send vacancies for all voids via email", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Ask emergency for a hand over from the weekend and to come into the office today to hand in all paperwork from the week before ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check team up and add anything extra to the white board for the week ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check with shaila what service charges have been paid and update CRM and google drive log", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: " check nest and ensure all property heating and hot water is on and working", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check if fixiit has had any new reported issues - Add to CRM", targetDuration: 20, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs are for the landlord and management agencies send an email to report the repair and book a tradesman with them.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "11.00-12pm", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Ask Amaani if all claims are active for housing benefit if any concerns call housing benefit ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: " receive photos from support workers regarding fire risk this is to include photos of outside bins, boiler screen and boiler pressure, any repairs needed. Photo of front of house from the road and photo of back garden and side entrances.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails throughout the day, do not close the outlook app, make sure emails are replied to straight away. If you do not know what to reply, ask Amaani, Leticia or Shaila", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs needed urgently call-in the contractor and send Burton to property if no staff onsite.", targetDuration: 30, priority: "Urgent", assignedTo: "Leticia" },
    { title: "View ring cameras and play back is working on all cameras ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "check all if HIK cameras and make sure all working and play back visible", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "12pm - 3pm", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "12:30-13:30 STAFF LUNCHES", isHeader: true, targetDuration: 0, priority: "Low", assignedTo: "Leticia" },
    { title: "  12:30-13:30 staff lunches (use sign to say when you will be back if only one person in office)", targetDuration: 60, priority: "Low", assignedTo: "Leticia" },
    { title: "Update board vacancies, check if anything new needs to be added from team up.", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check council tax online check there are no notices or missed payments ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "3pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check in with Shaila 4pm talk about any problems that may have come about", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "4pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B\u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "clean office desks with Dettol wipes, empty bins and declutter empty shredder, vacuum floor, file away all paperwork and take out rubbish.", targetDuration: 45, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check all emails and reply to any before leaving ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check google chats and reply to all messages ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check team up and update white board if anything new has been added ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check nest and make sure all heating is working correctly ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check Hik and ring and make sure all cameras are working ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Hand over to emergency anything they need to know", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Get a end of day hand over from support worker ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Get a hand over from burton", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Closing down the office:", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to closed", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door and close window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Close blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Put all paperwork and laptops away", targetDuration: 10, priority: "Medium", assignedTo: "Leticia" },
    { title: "Set alarm", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door ", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" }
  ],
  Tuesday: [
    { title: "TUESDAY", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Opening the office", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to open", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "10am-11am", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: " Check emails and reply to any new emails from last night and this morning", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Open up google chats and keep it open all day ", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check homeless support emails", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check office mobile/ landline returns any missed calls and reply to messages and whatsapp.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Send vacancies for all voids via email", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Ask emergency for a hand over from the weekend and to come into the office today to hand in all paperwork from the week before ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check team up and add anything extra to the white board for the week ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check with shaila what service charges have been paid and update CRM and google drive log", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: " check nest and ensure all property heating and hot water is on and working", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check if fixiit has had any new reported issues - Add to CRM", targetDuration: 20, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs are for the landlord and management agencies send an email to report the repair and book a tradesman with them.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "11.00-12pm", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Ask Amaani if all claims are active for housing benefit if any concerns call housing benefit ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: " receive photos from support workers regarding fire risk this is to include photos of outside bins, boiler screen and boiler pressure, any repairs needed. Photo of front of house from the road and photo of back garden and side entrances.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails throughout the day, do not close the outlook app, make sure emails are replied to straight away. If you do not know what to reply, ask Amaani, Leticia or Shaila", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs needed urgently call-in the contractor and send Burton to property if no staff onsite.", targetDuration: 30, priority: "Urgent", assignedTo: "Leticia" },
    { title: "View ring cameras and play back is working on all cameras ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "check all if HIK cameras and make sure all working and play back visible", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "12pm - onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "12:30-13:30 STAFF LUNCHES", isHeader: true, targetDuration: 0, priority: "Low", assignedTo: "Leticia" },
    { title: "  12:30-13:30 staff lunches (use sign to say when you will be back if only one person in office)", targetDuration: 60, priority: "Low", assignedTo: "Leticia" },
    { title: "Update board vacancies, check if anything new needs to be added from team up.", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check council tax online check there are no notices or missed payments ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "3pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check in with Shaila 4pm talk about any problems that may have come about", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Grey bins Geraldine- get residents to ensure bin lids are closed and no black bags on top of bins for next day collection, call a resident and get them to face time when they go and check the bins. Also can check on the camera ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "Grey bins little green lanes need to be put onto the path at the front of the house get support worker to do or call a resident and get them to do while on the phone to them what this on the camera also", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "4pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B\u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "clean office desks with Dettol wipes, empty bins and declutter empty shredder, vacuum floor, file away all paperwork and take out rubbish.", targetDuration: 45, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check all emails and reply to any before leaving ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check google chats and reply to all messages ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check team up and update white board if anything new has been added ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check nest and make sure all heating is working correctly ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check Hik and ring and make sure all cameras are working ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Hand over to emergency anything they need to know", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Get a end of day hand over from support worker ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Get a hand over from burton", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Closing down the office:", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to closed", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door and close window ", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Put all paperwork and laptops away", targetDuration: 10, priority: "Medium", assignedTo: "Leticia" },
    { title: "Set alarm and lock front door ", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" }
  ],
  Wednesday: [
    { title: "WEDNESDAY", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Opening the office", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to open", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "10am-11am", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: " Check emails and reply to any new emails from last night and this morning", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Open up google chats and keep it open all day ", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check homeless support emails", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check office mobile/ landline returns any missed calls and reply to messages and whatsapp.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Send vacancies for all voids via email", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Ask emergency for a hand over from the weekend and to come into the office today to hand in all paperwork from the week before ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check team up and add anything extra to the white board for the week ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check with shaila what service charges have been paid and update CRM and google drive log", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: " check nest and ensure all property heating and hot water is on and working", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check if fixiit has had any new reported issues - Add to CRM", targetDuration: 20, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs are for the landlord and management agencies send an email to report the repair and book a tradesman with them.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "11.00-12pm", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Ask Amaani if all claims are active for housing benefit if any concerns call housing benefit ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: " receive photos from support workers regarding fire risk this is to include photos of outside bins, boiler screen and boiler pressure, any repairs needed. Photo of front of house from the road and photo of back garden and side entrances.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails throughout the day, do not close the outlook app, make sure emails are replied to straight away. If you do not know what to reply, ask Amaani, Leticia or Shaila", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs needed urgently call-in the contractor and send Burton to property if no staff onsite.", targetDuration: 30, priority: "Urgent", assignedTo: "Leticia" },
    { title: "View ring cameras and play back is working on all cameras ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "check all if HIK cameras and make sure all working and play back visible", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "12pm - onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "12:30-13:30 STAFF LUNCHES", isHeader: true, targetDuration: 0, priority: "Low", assignedTo: "Leticia" },
    { title: "  12:30-13:30 staff lunches (use sign to say when you will be back if only one person in office)", targetDuration: 60, priority: "Low", assignedTo: "Leticia" },
    { title: "Update board vacancies, check if anything new needs to be added from team up.", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check council tax online check there are no notices or missed payments ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "3pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check in with Shaila 4pm talk about any problems that may have come about", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Get a tenant to put the bins for little green lanes back into the garden and check it has been emptied ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Get a tenant to check both bins are outside geraldine road and that it has been emptied ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "If the bins have not been emptied call the council and log it as a none collection and ask if to be collected if they do not give you a day this will be done the bins have to go back onto the path ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "4pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B\u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "clean office desks with Dettol wipes, empty bins and declutter empty shredder, vacuum floor, file away all paperwork and take out rubbish.", targetDuration: 45, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check all emails and reply to any before leaving ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check google chats and reply to all messages ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check team up and update white board if anything new has been added ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check nest and make sure all heating is working correctly ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check Hik and ring and make sure all cameras are working ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Hand over to emergency anything they need to know", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Get a end of day hand over from support worker ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Get a hand over from burton", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Closing down the office:", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to closed", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door and close window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Close blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Put all paperwork and laptops away", targetDuration: 10, priority: "Medium", assignedTo: "Leticia" },
    { title: "Set alarm", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door ", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" }
  ],
  Thursday: [
    { title: "THURSDAY", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Opening the office", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to open", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "10am-11am", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: " Check emails and reply to any new emails from last night and this morning", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Open up google chats and keep it open all day ", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check homeless support emails", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check office mobile/ landline returns any missed calls and reply to messages and whatsapp.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Send vacancies for all voids via email", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Ask emergency for a hand over from the weekend and to come into the office today to hand in all paperwork from the week before ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check team up and add anything extra to the white board for the week ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check with shaila what service charges have been paid and update CRM and google drive log", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: " check nest and ensure all property heating and hot water is on and working", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check if fixiit has had any new reported issues - Add to CRM", targetDuration: 20, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs are for the landlord and management agencies send an email to report the repair and book a tradesman with them.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "11.00-12pm", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Ask Amaani if all claims are active for housing benefit if any concerns call housing benefit ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: " receive photos from support workers regarding fire risk this is to include photos of outside bins, boiler screen and boiler pressure, any repairs needed. Photo of front of house from the road and photo of back garden and side entrances.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails throughout the day, do not close the outlook app, make sure emails are replied to straight away. If you do not know what to reply, ask Amaani, Leticia or Shaila", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs needed urgently call-in the contractor and send Burton to property if no staff onsite.", targetDuration: 30, priority: "Urgent", assignedTo: "Leticia" },
    { title: "View ring cameras and play back is working on all cameras ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "check all if HIK cameras and make sure all working and play back visible", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "12pm - onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "12:30-13:30 STAFF LUNCHES", isHeader: true, targetDuration: 0, priority: "Low", assignedTo: "Leticia" },
    { title: "  12:30-13:30 staff lunches (use sign to say when you will be back if only one person in office)", targetDuration: 60, priority: "Low", assignedTo: "Leticia" },
    { title: "Update board vacancies, check if anything new needs to be added from team up.", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check council tax online check there are no notices or missed payments ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "3pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check in with Shaila 4pm talk about any problems that may have come about", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Grey bins Moseley need to go out onto path get support worker to do if he is there or on shift if he is not face time residents and get them to take bins out while on facetime to you and put on path out the front they are kept in the side alley.check cameras to see if done ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "4pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B\u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "clean office desks with Dettol wipes, empty bins and declutter empty shredder, vacuum floor, file away all paperwork and take out rubbish.", targetDuration: 45, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check all emails and reply to any before leaving ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check google chats and reply to all messages ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check team up and update white board if anything new has been added ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check nest and make sure all heating is working correctly ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check Hik and ring and make sure all cameras are working ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Hand over to emergency anything they need to know", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Get a end of day hand over from support worker ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Get a hand over off burton", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Closing down the office:", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to closed", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door and close window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Close blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Put all paperwork and laptops away", targetDuration: 10, priority: "Medium", assignedTo: "Leticia" },
    { title: "Set alarm", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door ", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" }
  ],
  Friday: [
    { title: "FRIDAY", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Opening the office", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to open", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "10am-11am", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: " Check emails and reply to any new emails from last night and this morning", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Open up google chats and keep it open all day ", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check homeless support emails", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check office mobile/ landline returns any missed calls and reply to messages and whatsapp.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Send vacancies for all voids via email", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Ask emergency for a hand over from the weekend and to come into the office today to hand in all paperwork from the week before ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check team up and add anything extra to the white board for the week ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check with shaila what service charges have been paid and update CRM and google drive log", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: " check nest and ensure all property heating and hot water is on and working", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check if fixiit has had any new reported issues - Add to CRM", targetDuration: 20, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs are for the landlord and management agencies send an email to report the repair and book a tradesman with them.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "11.00-12pm", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Ask Amaani if all claims are active for housing benefit if any concerns call housing benefit ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: " receive photos from support workers regarding fire risk this is to include photos of outside bins, boiler screen and boiler pressure, any repairs needed. Photo of front of house from the road and photo of back garden and side entrances.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails throughout the day, do not close the outlook app, make sure emails are replied to straight away. If you do not know what to reply, ask Amaani, Leticia or Shaila", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs needed urgently call-in the contractor and send Burton to property if no staff onsite.", targetDuration: 30, priority: "Urgent", assignedTo: "Leticia" },
    { title: "View ring cameras and play back is working on all cameras ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "check all if HIK cameras and make sure all working and play back visible", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "12pm - onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "12:30-13:30 STAFF LUNCHES", isHeader: true, targetDuration: 0, priority: "Low", assignedTo: "Leticia" },
    { title: "  12:30-13:30 staff lunches (use sign to say when you will be back if only one person in office)", targetDuration: 60, priority: "Low", assignedTo: "Leticia" },
    { title: "Update board vacancies, check if anything new needs to be added from team up.", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check council tax online check there are no notices or missed payments ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "3pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check in with Shaila 4pm talk about any problems that may have come about", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Get a tenant to put the bins back onto the garden from the path ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "If the bins have not been emptied then call the council and log it as a none collection if they do not give you a day they will return you may need to get the bins to be put back onto the path", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "4pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B\u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "clean office desks with Dettol wipes, empty bins and declutter empty shredder, vacuum floor, file away all paperwork and take out rubbish.", targetDuration: 45, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check all emails and reply to any before leaving ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check google chats and reply to all messages ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check team up and update white board if anything new has been added ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check nest and make sure all heating is working correctly ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check Hik and ring and make sure all cameras are working ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Hand over to emergency anything they need to know", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Get a end of day hand over from support worker ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Get a hand over from burton", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Closing down the office:", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to closed and close blinds ", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door and close window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Set alarm and lock office door ", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Extra tasks", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Support notes", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker support notes throughout the day ", targetDuration: 60, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check they have the signature attached to the support note ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Make a copy of support note that has been merged and add it to goggle driver combined office folder", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Copy the link for support note from office folder and upload it to entry on support plans on CRM", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check this every hour for the property the support worker is working from", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check that the UC photos have been put into the google drive uc folders for each tenant after they have been seen ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check they have completed the day before schedule in full and the accommodation check list ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Upload the document copy link to CRM for accommodation checks for the day before support.", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Housing benefit/ new move ins with UC", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Complete housing benefit application for any new move ins ", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Save the housing benefit application form log when completed ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Copy the submission ref number and make a log on CRM for the application made", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Complete the google chats log on housing benefits (use the template)", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Log the new tenant onto CRM residents page ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Log new move in information onto the support workers google drive tenants information sheets for that new move in", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Ensure all the licence agreement and authorisation form is filled in ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Make sure you have a universal credit photo for the new move n ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "If they do not have a previous statement with their name on you must get a photo of the home page and the journal that displays their names ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Use cam scanner to save the documents to google drive tenants page ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "Upload the evidence to housing benefit once the application has been completed ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "New UASC move in", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Log the new move in on the google chat for new placements (use the template)", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Log new move in information onto the support workers google drive tenants information sheets for that new move in\u200B", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Log the new residents onto the CRM resident page ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" }
  ]
};

export const ROUTINE_TITLES = Array.from(new Set(
  Object.values(WEEKLY_ROUTINES).flatMap(day => day.map(r => (r.title || "").trim()))
));

export const QUICK_TASKS = [
  'open the blinds', 'open the window', 'flip sign to open',
  'flip sign to closed', 'lock front door and close window', 'close blinds',
  'put all paperwork and laptops away', 'set alarm', 'lock front door',
  'set alarm and lock front door', 'flip sign to closed and close blinds',
  'set alarm and lock office door'
];
