export const WEEKLY_ROUTINES = {
  Monday: [
    { title: "MONDAY", isHeader: true, targetDuration: 0, priority: "Medium", assignedTo: "Leticia" },
    { title: "Opening the office ", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Open the window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to open", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "10am-11am", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: " Check emails and reply to any new emails from last night and this morning", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Open up google chats and keep it open all day ", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check homeless support emails", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check office mobile/ landline returns any missed calls and reply to messages and whatsapp.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Send vacancies for all voids via email", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Ask emergency for a hand over from the weekend and to come into the office today to hand in all paperwork from the week before ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check team up and add anything extra to the white board for the week ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check with shaila what service charges have been paid and update CRM and google drive log", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: " check nest and ensure all property heating and hot water is on and working", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check if fixiit has had any new reported issues - Add to CRM", targetDuration: 20, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs are for the landlord and management agencies send an email to report the repair and book a tradesman with them.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "11.00-12pm", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Ask Amaani if all claims are active for housing benefit if any concerns call housing benefit ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: " receive photos from support workers regarding fire risk this is to include photos of outside bins, boiler screen and boiler pressure, any repairs needed. Photo of front of house from the road and photo of back garden and side entrances.", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails throughout the day, do not close the outlook app, make sure emails are replied to straight away. If you do not know what to reply, ask Amaani, Leticia or Shaila", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "If any repairs needed urgently call-in the contractor and send Burton to property if no staff onsite.", targetDuration: 30, priority: "Urgent", assignedTo: "Leticia" },
    { title: "View ring cameras and play back is working on all cameras ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "check all if HIK cameras and make sure all working and play back visible", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "12pm - 3pm", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "  12:30-13:30 staff lunches (use sign to say when you will be back if only one person in office)", targetDuration: 60, priority: "Low", assignedTo: "Leticia" },
    { title: "Update board vacancies, check if anything new needs to be added from team up.", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check council tax online check there are no notices or missed payments ", targetDuration: 20, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder ", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "3pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check in with Shaila 4pm talk about any problems that may have come about", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Check support worker has uploaded universal credit photos into google drive for all completed support so far check for change of address photo, statement photo, journal photo and to do list photo\u200B\u200B", targetDuration: 60, priority: "High", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "4pm onwards", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check support notes have been merged from support worker make a copy of this document and save to combined google drive folder \u200B\u200B", targetDuration: 30, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check emails every 15 minutes\u200B\u200B\u200B\u200B\u200B\u200B", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "clean office desks with Dettol wipes, empty bins and declutter empty shredder, vacuum floor, file away all paperwork and take out rubbish.", targetDuration: 45, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check all emails and reply to any before leaving ", targetDuration: 30, priority: "High", assignedTo: "Leticia" },
    { title: "Check google chats and reply to all messages ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check team up and update white board if anything new has been added ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check nest and make sure all heating is working correctly ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Check Hik and ring and make sure all cameras are working ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Hand over to emergency anything they need to know", targetDuration: 15, priority: "High", assignedTo: "Leticia" },
    { title: "Get a end of day hand over from support worker ", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Get a hand over from burton", targetDuration: 15, priority: "Medium", assignedTo: "Leticia" },
    { title: "Closing down the office:", isHeader: true, targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Flip sign to closed", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door and close window", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Close blinds", targetDuration: 5, priority: "Medium", assignedTo: "Leticia" },
    { title: "Put all paperwork and laptops away", targetDuration: 10, priority: "Medium", assignedTo: "Leticia" },
    { title: "Set alarm", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" },
    { title: "Lock front door ", targetDuration: 2, priority: "Medium", assignedTo: "Leticia" }
  ],
  Tuesday: [],
  Wednesday: [],
  Thursday: [],
  Friday: []
};

export const ROUTINE_TITLES = Array.from(new Set(
  Object.values(WEEKLY_ROUTINES).flatMap(day => day.map(r => (r.title || "").trim()))
));
